(()=>{"use strict";
const app=document.getElementById("app"),toast=document.getElementById("toast"),alerts={};
const S=()=>window.PorPertoStore,L=()=>S().ensure(S().load()),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),day=()=>new Date().toISOString().slice(0,10),mins=t=>S().mins(t),ts=m=>m.schedule||[],photo=m=>m.photo||"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="500" height="320"><rect width="100%" height="100%" fill="#e8e3d6"/><circle cx="250" cy="150" r="70" fill="white"/><text x="250" y="160" text-anchor="middle" font-size="30" font-family="Arial" fill="#173b2a">Remédio</text></svg>');
function msg(x){toast.textContent=x;toast.classList.add("show");clearTimeout(msg.t);msg.t=setTimeout(()=>toast.classList.remove("show"),3500)}
function taken(id,t){return S().taken(id,t)==="taken"}
function dose(s){let n=new Date().getHours()*60+new Date().getMinutes(),a=[];s.medicines.forEach(m=>{if(m.frequency?.type==="as_needed")return;if(m.frequency?.type==="weekly"&&!(m.frequency.days||[]).includes(new Date().getDay()))return;ts(m).forEach(t=>{if(mins(t)>=n&&!taken(m.id,t))a.push({m,t,n:mins(t)})})});return a.sort((a,b)=>a.n-b.n)[0]}
function apt(s){return s.appointments.filter(a=>new Date(a.date+"T"+a.time)>=new Date).sort((a,b)=>new Date(a.date+"T"+a.time)-new Date(b.date+"T"+b.time))[0]}
function fmt(a){return new Date(a.date+"T"+a.time).toLocaleDateString("pt-BR",{day:"2-digit",month:"long"})+" às "+a.time}
function home(){let s=L(),e=s.elder,d=dose(s),a=apt(s);app.innerHTML=`<header class="topbar"><div><span class="eyebrow">POR PERTO</span><h1>Olá, ${esc(e.name)}.</h1></div><a class="header-link" href="painel.html">Família</a></header><section class="welcome-card"><strong>Estamos cuidando de você.</strong><span>Veja o que precisa de atenção agora.</span></section><section class="section-block"><h2>Próximo remédio</h2>${d?`<article class="care-card medication-card"><img src="${photo(d.m)}" alt=""><div class="care-content"><span class="status-badge">HORA DO REMÉDIO</span><h3>${esc(d.m.name)}</h3><p class="big-detail">${esc(d.m.dose||"Conforme orientação")}</p><p class="time-detail">Hoje às <strong>${d.t}</strong></p><div class="action-row"><button class="primary-btn giant" data-action="take" data-id="${d.m.id}" data-time="${d.t}">TOMEI</button><button class="secondary-btn" data-action="med" data-id="${d.m.id}">VER REMÉDIO</button></div></div></article>`:`<article class="care-card success-card"><div class="big-icon">✓</div><div><h3>Nenhum remédio pendente</h3><p>Por enquanto está tudo certo.</p></div></article>`}</section><section class="section-block"><h2>Próxima consulta</h2>${a?`<article class="care-card"><div class="care-content"><span class="status-badge neutral">CONSULTA</span><h3>${esc(a.specialty)}</h3><p class="big-detail">${esc(a.doctor)}</p><p>${esc(a.location)}</p><p class="time-detail">${fmt(a)}</p><button class="secondary-btn full" data-action="apt" data-id="${a.id}">VER CONSULTA</button></div></article>`:`<article class="care-card"><h3>Nenhuma consulta próxima</h3><p>A família avisará quando houver uma nova consulta.</p></article>`}</section><button class="sos-btn" data-action="sos">PRECISO DE AJUDA</button><p class="footer-note">Se precisar, aperte o botão vermelho. Sua família será avisada.</p>`}
function med(id){let s=L(),m=s.medicines.find(x=>x.id===id);if(!m)return home();app.innerHTML=`<header class="page-header"><button class="back-btn" data-action="home">← Voltar</button><h1>Remédio</h1></header><article class="detail-card"><img class="detail-image" src="${photo(m)}" alt=""><span class="status-badge">REMÉDIO</span><h2>${esc(m.name)}</h2><p class="big-detail">${esc(m.dose||"Conforme orientação")}</p><p><strong>Horários:</strong> ${ts(m).join(", ")}</p><button class="primary-btn giant full" data-action="take" data-id="${m.id}" data-time="${ts(m)[0]||""}">TOMEI</button></article>`}
function appointment(id){let s=L(),a=s.appointments.find(x=>x.id===id);if(!a)return home();app.innerHTML=`<header class="page-header"><button class="back-btn" data-action="home">← Voltar</button><h1>Consulta</h1></header><article class="detail-card"><span class="status-badge neutral">CONSULTA</span><h2>${esc(a.specialty)}</h2><p class="big-detail">${esc(a.doctor)}</p><p>${esc(a.location)}</p><p class="time-detail">${fmt(a)}</p>${a.returnDate?`<p><strong>Retorno:</strong> ${new Date(a.returnDate+"T12:00:00").toLocaleDateString("pt-BR")}</p>`:""}<button class="primary-btn giant full" data-action="understand" data-id="${a.id}">ENTENDI</button></article>`}
function sos(){let s=L(),r=s.responsible||{},c=s.emergencyContacts||[];S().sos();app.innerHTML=`<header class="page-header"><button class="back-btn" data-action="home">← Voltar</button><h1>Ajuda</h1></header><article class="sos-flow"><div class="big-icon danger">!</div><h2 id="st">Enviando localização...</h2><p id="sx">Aguarde um instante.</p></article>`;setTimeout(()=>{st.textContent="Avisando família...";sx.textContent="Estamos avisando quem cuida de você."},1000);setTimeout(()=>{st.textContent="Pronto!";sx.textContent="Sua família foi avisada.";document.querySelector(".sos-flow").insertAdjacentHTML("beforeend",`<a class="call-btn" href="tel:${esc(r.phone)}">LIGAR PARA ${esc(r.name||"FAMÍLIA")}</a>${c.map(x=>`<a class="secondary-btn full" href="tel:${esc(x.phone)}">LIGAR PARA ${esc(x.name)}</a>`).join("")}<button class="secondary-btn full" data-action="home">VOLTAR AO INÍCIO</button>`)},2200)}
function take(id,t){S().markTaken(id,t);delete alerts[day()+"|"+id+"|"+t];msg("Pronto. Registramos que você tomou o remédio.");home()}
function check(){let s=L(),n=new Date().getHours()*60+new Date().getMinutes(),r=Number(s.settings?.reminderRepeatMinutes||10);s.medicines.forEach(m=>ts(m).forEach(t=>{if(m.frequency?.type==="as_needed"||taken(m.id,t))return;let k=day()+"|"+m.id+"|"+t;if(n>=mins(t)&&(!alerts[k]||Date.now()-alerts[k]>=r*60000)){alerts[k]=Date.now();try{let C=AudioContext||webkitAudioContext,c=new C,o=c.createOscillator(),g=c.createGain();o.frequency.value=660;g.gain.value=.1;o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.5)}catch{}if("Notification"in window&&Notification.permission==="granted")try{new Notification("Hora do remédio",{body:m.name+" — "+m.dose})}catch{}msg("Hora do remédio: "+m.name)}}))}
app.addEventListener("click",e=>{let x=e.target.closest("[data-action]");if(!x)return;let a=x.dataset.action;if("Notification"in window&&Notification.permission==="default")Notification.requestPermission().catch(()=>{});if(a==="home")home();if(a==="take")take(x.dataset.id,x.dataset.time);if(a==="med")med(x.dataset.id);if(a==="apt")appointment(x.dataset.id);if(a==="understand"){S().markApt(x.dataset.id);msg("Consulta registrada.");home()}if(a==="sos")sos()});
window.addEventListener("storage",e=>{if(e.key===S().STORAGE_KEY)home()});home();check();setInterval(check,15000);
})();