import React,{useEffect,useState}from"react";
import{supabase}from"./supabase";
import"./styles.css";

const EMPTY={esf:{full_name:"",email:"",password:"",phone:"",esf_name:"",code:"",address:""},doctor:{full_name:"",email:"",password:"",phone:"",esf_id:""},patient:{full_name:"",preferred_name:"",birth_date:"",cpf:"",phone:"",address:"",notes:"",esf_id:"",doctor_id:""}};

function Field({label,value,onChange,type="text",required=false}){return <label className="field"><span>{label}</span><input type={type} value={value??""} onChange={onChange} required={required}/></label>}
function Select({label,value,onChange,items,doctor=false,required=false}){return <label className="field"><span>{label}</span><select value={value??""} onChange={onChange} required={required}><option value="">Selecione</option>{items.map(x=><option key={x.id} value={x.id}>{doctor?x.full_name:x.name}</option>)}</select></label>}
function Login(){const[e,setE]=useState(""),[p,setP]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false),[wait,setWait]=useState(0);
 useEffect(()=>{const until=Number(localStorage.getItem("por-perto-login-lockout")||0);if(until>Date.now()){const tick=()=>setWait(Math.ceil((until-Date.now())/1000));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)}localStorage.removeItem("por-perto-login-lockout")},[]);
 async function go(ev){ev.preventDefault();if(busy||wait>0)return;const attempts=Number(localStorage.getItem("por-perto-login-attempts")||0);if(attempts>=5){const until=Date.now()+15*60*1000;localStorage.setItem("por-perto-login-lockout",String(until));setWait(900);setErr("Muitas tentativas. Aguarde 15 minutos e tente novamente.");return}setBusy(true);setErr("");const{error}=await supabase.auth.signInWithPassword({email:e.trim().toLowerCase(),password:p});if(error){const next=attempts+1;localStorage.setItem("por-perto-login-attempts",String(next));if(next>=5){const until=Date.now()+15*60*1000;localStorage.setItem("por-perto-login-lockout",String(until));setWait(900);setErr("Muitas tentativas. Aguarde 15 minutos e tente novamente.")}else setErr("E-mail ou senha inválidos. Verifique os dados e tente novamente.")}else{localStorage.removeItem("por-perto-login-attempts");localStorage.removeItem("por-perto-login-lockout")}setBusy(false)}
 return <div className="auth-page"><div className="auth-card"><div className="brand"><span className="brand-mark">P</span><strong>Por Perto</strong></div><p className="eyebrow">Central de cuidado</p><h1>Entrar</h1><p>Acesse sua área de trabalho.</p><form onSubmit={go}><Field label="E-mail" type="email" value={e} onChange={x=>setE(x.target.value)} required/><Field label="Senha" type="password" value={p} onChange={x=>setP(x.target.value)} required/>{err&&<div className="error-box">{err}</div>}<button className="primary-btn full" disabled={busy||wait>0}>{wait>0?`AGUARDE ${wait}s`:busy?"ENTRANDO…":"ENTRAR"}</button></form></div></div>}

function App(){const[user,setUser]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let mounted=true;supabase.auth.getSession().then(async({data})=>{if(!mounted)return;if(data.session){setUser(data.session.user);const{data:p,error:e}=await supabase.from("profiles").select("*").eq("id",data.session.user.id).single();if(e)setError(e.message);else setProfile(p)}setLoading(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_,s)=>{setUser(s?.user||null);if(!s){setProfile(null);setLoading(false)}});return()=>{mounted=false;subscription.unsubscribe()}},[]);
 if(loading)return <div className="loading-screen">Carregando…</div>;if(!user)return <Login/>;if(!profile)return <div className="auth-page"><div className="auth-card"><h1>Perfil não encontrado</h1><p>{error||"Usuário sem perfil."}</p><button className="secondary-btn full" onClick={()=>supabase.auth.signOut()}>SAIR</button></div></div>;
 if(profile.role==="admin")return <Admin profile={profile}/>;if(profile.role==="esf")return <EsfPanel profile={profile}/>;if(profile.role==="doctor")return <DoctorPanel profile={profile}/>;
 return <div className="auth-page"><div className="auth-card"><h1>Acesso restrito</h1><button className="secondary-btn full" onClick={()=>supabase.auth.signOut()}>SAIR</button></div></div>}

function Shell({profile,title,subtitle,children}){return <div className="admin-shell"><aside className="admin-sidebar"><div className="brand"><span className="brand-mark">P</span><strong>Por Perto</strong></div><div className="user-mini"><div className="avatar">{profile.full_name.slice(0,2).toUpperCase()}</div><div><strong>{profile.full_name}</strong><span>{profile.role==="admin"?"Administrador":profile.role==="esf"?"ESF":"Doutor"}</span></div></div><button className="logout-btn" onClick={()=>supabase.auth.signOut()}>Sair</button></aside><main className="admin-main"><header className="admin-header"><div><p className="eyebrow">{profile.role==="admin"?"Painel administrativo":"Área de trabalho"}</p><h1>{title}</h1><p>{subtitle}</p></div><button className="secondary-btn" onClick={()=>supabase.auth.signOut()}>SAIR</button></header><section className="admin-content">{children}</section></main></div>}

function Modal({title,onClose,children}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose}>×</button></div>{children}</div></div>}
function Row({name,detail,action}){return <div className="admin-row"><div className="avatar">{name.slice(0,2).toUpperCase()}</div><div className="list-main"><strong>{name}</strong><span>{detail||"—"}</span></div>{action}</div>}
function Metric({label,value}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong></article>}

function Admin({profile}){const[esfs,setEsfs]=useState([]),[doctors,setDoctors]=useState([]),[patients,setPatients]=useState([]),[modal,setModal]=useState(null),[msg,setMsg]=useState("");
 const load=async()=>{const[a,b,c]=await Promise.all([supabase.from("esfs").select("*").order("name"),supabase.from("profiles").select("*").eq("role","doctor").order("full_name"),supabase.from("patients").select("*,esfs(name),doctor:profiles!patients_doctor_id_fkey(full_name)").order("full_name")]);setEsfs(a.data||[]);setDoctors(b.data||[]);setPatients(c.data||[]);setMsg(a.error?.message||b.error?.message||c.error?.message||"")};useEffect(()=>{load()},[]);
 const save=async ev=>{ev.preventDefault();setMsg("");let r;if(modal.type==="esf")r=await supabase.functions.invoke("manage-staff-user",{body:{...modal.data,kind:"esf"}});if(modal.type==="patient")r=await supabase.from("patients").insert({...modal.data,created_by:profile.id});if(r.error){let detail=r.error.message;try{if(r.error.context){const body=await r.error.context.json();detail=body?.error||detail}}catch{}setMsg(detail)}else{setMsg("Cadastro realizado.");setModal(null);load()}};
 return <Shell profile={profile} title="Gestão da rede" subtitle="Você cadastra as ESFs. Cada ESF terá seu próprio acesso."><div className="metric-grid"><Metric label="ESFs" value={esfs.length}/><Metric label="Doutores" value={doctors.length}/><Metric label="Pacientes" value={patients.length}/></div>{msg&&<div className="notice">{msg}</div>}<article className="panel-card"><div className="list-head"><div><p className="eyebrow">Unidades</p><h2>ESFs</h2></div><button className="primary-btn" onClick={()=>setModal({type:"esf",data:{...EMPTY.esf}})}>+ NOVA ESF</button></div>{esfs.map(x=><Row key={x.id} name={x.name} detail={x.phone||x.address}/>)}</article><article className="panel-card"><p className="eyebrow">Resumo</p><h2>Doutores e pacientes</h2><p>{doctors.length} doutores e {patients.length} pacientes cadastrados na rede.</p></article>{modal&&<Modal title="Nova ESF + acesso" onClose={()=>setModal(null)}><form onSubmit={save}><Field label="Nome da ESF" value={modal.data.esf_name} onChange={e=>setModal(m=>({...m,data:{...m.data,esf_name:e.target.value}}))} required/><Field label="Nome do responsável" value={modal.data.full_name} onChange={e=>setModal(m=>({...m,data:{...m.data,full_name:e.target.value}}))} required/><Field label="E-mail de login" type="email" value={modal.data.email} onChange={e=>setModal(m=>({...m,data:{...m.data,email:e.target.value}}))} required/><Field label="Senha inicial" type="password" value={modal.data.password} onChange={e=>setModal(m=>({...m,data:{...m.data,password:e.target.value}}))} required/><Field label="Código" value={modal.data.code} onChange={e=>setModal(m=>({...m,data:{...m.data,code:e.target.value}}))}/><Field label="Telefone" value={modal.data.phone} onChange={e=>setModal(m=>({...m,data:{...m.data,phone:e.target.value}}))}/><Field label="Endereço" value={modal.data.address} onChange={e=>setModal(m=>({...m,data:{...m.data,address:e.target.value}}))}/><button className="primary-btn full">CRIAR ESF E ACESSO</button></form></Modal>}</Shell>}

function EsfPanel({profile}){const[esf,setEsf]=useState(null),[doctors,setDoctors]=useState([]),[patients,setPatients]=useState([]),[modal,setModal]=useState(null),[msg,setMsg]=useState("");
 const load=async()=>{const{data:m}=await supabase.from("esf_members").select("esf_id").eq("user_id",profile.id).eq("role","manager").maybeSingle();if(!m){setMsg("ESF não vinculada.");return}const[e,d,p]=await Promise.all([supabase.from("esfs").select("*").eq("id",m.esf_id).single(),supabase.from("esf_members").select("user_id,role,profiles(full_name,phone)").eq("esf_id",m.esf_id).eq("role","doctor"),supabase.from("patients").select("*,doctor:profiles!patients_doctor_id_fkey(full_name)").eq("esf_id",m.esf_id).order("full_name")]);setEsf(e.data);setDoctors((d.data||[]).map(x=>({id:x.user_id,...x.profiles})));setPatients(p.data||[]);setMsg(e.error?.message||d.error?.message||p.error?.message||"")};useEffect(()=>{load()},[]);
 const save=async ev=>{ev.preventDefault();setMsg("");let r;if(modal.type==="doctor")r=await supabase.functions.invoke("manage-staff-user",{body:{...modal.data,kind:"doctor",esf_id:esf.id}});else r=await supabase.from("patients").insert({...modal.data,esf_id:esf.id,created_by:profile.id});if(r.error){let detail=r.error.message;try{if(r.error.context){const body=await r.error.context.json();detail=body?.error||detail}}catch{}setMsg(detail)}else{setMsg("Cadastro realizado.");setModal(null);load()}};
 return <Shell profile={profile} title={esf?.name||"Minha ESF"} subtitle="Cadastre doutores e pacientes desta unidade."><div className="metric-grid"><Metric label="Doutores" value={doctors.length}/><Metric label="Pacientes" value={patients.length}/></div>{msg&&<div className="notice">{msg}</div>}<article className="panel-card"><div className="list-head"><div><p className="eyebrow">Equipe</p><h2>Doutores</h2></div><button className="primary-btn" onClick={()=>setModal({type:"doctor",data:{...EMPTY.doctor}})}>+ NOVO DOUTOR</button></div>{doctors.map(x=><Row key={x.id} name={x.full_name} detail={x.phone}/>)}</article><article className="panel-card"><div className="list-head"><div><p className="eyebrow">Atendimento</p><h2>Pacientes</h2></div><button className="primary-btn" onClick={()=>setModal({type:"patient",data:{...EMPTY.patient}})}>+ NOVO PACIENTE</button></div>{patients.map(x=><Row key={x.id} name={x.preferred_name||x.full_name} detail={x.doctor?.full_name}/>)}</article>{modal&&<Modal title={modal.type==="doctor"?"Novo doutor + acesso":"Novo paciente"} onClose={()=>setModal(null)}><form onSubmit={save}>{modal.type==="doctor"?<><Field label="Nome completo" value={modal.data.full_name} onChange={e=>setModal(m=>({...m,data:{...m.data,full_name:e.target.value}}))} required/><Field label="E-mail de login" type="email" value={modal.data.email} onChange={e=>setModal(m=>({...m,data:{...m.data,email:e.target.value}}))} required/><Field label="Senha inicial" type="password" value={modal.data.password} onChange={e=>setModal(m=>({...m,data:{...m.data,password:e.target.value}}))} required/><Field label="Telefone" value={modal.data.phone} onChange={e=>setModal(m=>({...m,data:{...m.data,phone:e.target.value}}))}/></>:<><Field label="Nome completo" value={modal.data.full_name} onChange={e=>setModal(m=>({...m,data:{...m.data,full_name:e.target.value}}))} required/><Field label="Nome de preferência" value={modal.data.preferred_name} onChange={e=>setModal(m=>({...m,data:{...m.data,preferred_name:e.target.value}}))}/><Field label="Nascimento" type="date" value={modal.data.birth_date} onChange={e=>setModal(m=>({...m,data:{...m.data,birth_date:e.target.value}}))}/><Field label="CPF" value={modal.data.cpf} onChange={e=>setModal(m=>({...m,data:{...m.data,cpf:e.target.value}}))}/><Field label="Telefone" value={modal.data.phone} onChange={e=>setModal(m=>({...m,data:{...m.data,phone:e.target.value}}))}/><Field label="Endereço" value={modal.data.address} onChange={e=>setModal(m=>({...m,data:{...m.data,address:e.target.value}}))}/><Select label="Doutor responsável" value={modal.data.doctor_id} onChange={e=>setModal(m=>({...m,data:{...m.data,doctor_id:e.target.value}}))} items={doctors} doctor/><Field label="Observações" value={modal.data.notes} onChange={e=>setModal(m=>({...m,data:{...m.data,notes:e.target.value}}))}/></>}<button className="primary-btn full">SALVAR</button></form></Modal>}</Shell>}

function DoctorPanel({profile}){const[patients,setPatients]=useState([]);useEffect(()=>{supabase.from("patients").select("*,esfs(name)").eq("doctor_id",profile.id).order("full_name").then(({data})=>setPatients(data||[]))},[]);return <Shell profile={profile} title="Meus pacientes" subtitle="Pacientes vinculados ao seu atendimento."><article className="panel-card">{patients.map(x=><Row key={x.id} name={x.preferred_name||x.full_name} detail={x.esfs?.name||x.phone}/>) }{!patients.length&&<p>Nenhum paciente vinculado.</p>}</article></Shell>}

export default App;